# Generated by Django 4.0.1 on 2022-01-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
